version: '3'

services:
    app:
        build:
            context: .
            dockerfile: PDS-MatEduca/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
        depends_on:
            - db

    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: your_root_password
            MYSQL_DATABASE: your_database_name
            MYSQL_USER: your_user
            MYSQL_PASSWORD: your_password

    web:
        image: php:7.4-apache
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./laravel-vue/apache-config.conf:/etc/apache2/sites-available/000-default.conf
        depends_on:
            - app

volumes:
    db_data:
